sudo: false

language: java

script:
  - ./gradlew project

cache:
  directories:
    - $HOME/.gradle

notifications:
  email:
    recipients:
      - marcus@fihlon.ch
    on_success: always
    on_failure: always
